### ISSUE TITLE
ImageJ not able to open generated DICOM

### ISSUE THREAD

**Issue by andreasala98** [a-parida12/pdf2dcm#19]
Hi everyone,
first of all, thanks for the effort you are putting into this library.

I have a (coloured) PDF containing a medical report which I need to store back into PACS as a secondary capture in an automated way. Therefore I was looking for some pdf2dicom converters and I came across this repo.

I can successfully generate a dicom image from a pdf using your python package, but
- ImageJ won't open the newly generated image ("Unable to decode DICOM header"). Is it a ImageJ "bug" or are there some problems with the dicom fields? The dicom fields were taken from an actual CT image that opens correctly via ImageJ
- Horos will open the image, but it looks really weird (see attachment below). Am I missing something or maybe the conversion from RGB pdf is not implemented yet? 

[Here](https://www.tug.org/pracjourn/2007-4/walden/color.pdf) the link to the sample pdf I am trying to convert
Thanks 

Andrea

<img width="411" alt="view_from_horos" src="https://user-images.githubusercontent.com/62481947/172629442-1228c5a5-91cc-42ba-ae62-477c98067c9a.png">

**Comment by a-parida12** [comment]
Hi, @andreasala98 Thanks for giving the `pdf2dcm` a try!

As I understand that you are looking to store a secondary capture(https://dicom.nema.org/dicom/2013/output/chtml/part03/sect_A.8.html) which is a pending feature that I intend to support. 

The converter you tried to use for pdf --> encapsulated pdf, which I am not sure is good for the colored image.

Given your interest in the feature, I will try and prioritize the already open #1 . So maybe you can come back and try it after the weekend.

**Comment by a-parida12** [comment]
@andreasala98 It would be super great if you could share PDF DICOM samples that work fine for the ImageJ viewer so I could take a look at that as well.

**Comment by andreasala98** [comment]
Sure, [here](https://physionet.org/content/images/1.0.0/E1154S7I.dcm) it is.

**Comment by a-parida12** [comment]
Does https://github.com/a-parida12/pdf2dcm#pdf-to-rgb-secondary-capture-dcm from the `pdf2dcm` [v0.2.0](https://pypi.org/project/pdf2dcm/) help you?

**Comment by a-parida12** [comment]
@andreasala98 I think your issue was solved so closing this issue.

If not, feel free to reopen the issue and provide the additional information.
