### ISSUE TITLE
[Documentation] Initial Draft

### ISSUE THREAD

**Issue by a-parida12** [a-parida12/pdf2dcm#27]
- [ ] create automatic CI-based documents pages from docstrings

**Comment by trkohler** [comment]
hello @a-parida12 !
do you plan to make this issue available for hacktoberfest?

**Comment by a-parida12** [comment]
@trkohler yes I do. Do you want to help in setting up the documentation for the repo?

**Comment by trkohler** [comment]
yes, I think I would. We may publish it on netlify / github pages, however you prefer.

**Comment by a-parida12** [comment]
@trkohler I assigned the issue to you. Feel free to start after 1st October.

I think GitHub pages is better as it will not add external dependency and  requires no setting up credentials etc. 

What do you prefer `markdown` or `html` based? Do you have some templates in mind?

**Comment by trkohler** [comment]
I'd investigate the options and bring it back to our discussion.

**Comment by trkohler** [comment]
i thought to try [pdoc3](https://pdoc3.github.io/pdoc/), wdyt?

**Comment by a-parida12** [comment]
`pdoc3` LGTM. just wanted to know if it is possible to add examples code snippets also with it, cause couldn't find any reference to it. But maybe that can be an update on the API documentation?

**Comment by trkohler** [comment]
hello again! not sure how to test the pipeline because it's not running on VM for some reason when I contribute PR with a fork.
May I ask to take a look? Maybe pipeline is visible for you?

**Comment by trkohler** [comment]
pdoc3 adds source code to the doc (i checked it).
regarding code snippets pdoc3 supports markdown and markdown supports code snippets so you may try to add those, it should work.
![Screenshot 2022-10-02 at 13 38 07](https://user-images.githubusercontent.com/49440211/193452056-b9fa3bf2-790a-4ab1-a5b7-7efd08e557fd.png)

**Comment by a-parida12** [comment]
thanks, I merged it!

**Comment by trkohler** [comment]
seems like [it doesn't work properly](https://a-parida12.github.io/pdf2dcm/)
i think it's because [the root is already occupied by other static](https://a-parida12.github.io/)
i'd try to debug that and prepare a fix soon

**Comment by a-parida12** [comment]
Currently it is at https://a-parida12.github.io/pdf2dcm/pdf2dcm
