### ISSUE TITLE
Should generate new SOPInstanceUID

### ISSUE THREAD

**Issue by fraser29** [a-parida12/pdf2dcm#35]
I don't think that the SOPInstanceUID should be taken from the template dicom. _SOPInstanceUID should always be unique._ 
If the template dicom is a 'true' dicom in PACs then one of the two will not be seen by PACs. 

https://github.com/a-parida12/pdf2dcm/blob/82c4da0148561e8c40d63ea1e2944b7c489d29fa/pdf2dcm/base.py#L24

**Comment by a-parida12** [comment]
@fraser29 I was meaning to do the changes for some time. Could you please put a pull to the branch https://github.com/a-parida12/pdf2dcm/tree/35-should-generate-new-sopinstanceuid instead of the main branch?

Thank you so much for contributing.

**Comment by a-parida12** [comment]
TODOs for the resolution-

- [ ]  merge @fraser29 branch to branch 35
- [ ]  format the changes
- [ ]  update the unit tests
- [ ]  update the README
